Ce notebook contient des tests sur 2 des meilleurs modèles (GPT-oss et Phi-3) avec un prompt contenant plusieurs entrées du dictionnaire. Les mots ainsi que leur catégorie, leur définition et leur étymologie viennent du fichier Kaikki suivant : fr-extract.jsonl.gz. Le fichier étant trop lourd, on ne travaille que sur des chunks, c'est-à-dire que le modèle a, au maximum, traité 10 mots.

A la fin on obtient un csv qui ressemble beaucoup à parsed_1.tsv, mais sur qu'un seul chunk et avec les réponses de GPT-oss.

# Installation et configuration

In [ ]:
# Uniquement pour Colab, sinon télécharger Ollama https://ollama.com/download
!sudo apt update
!sudo apt install -y pciutils
!sudo apt-get install zstd
!curl -fsSL https://ollama.com/install.sh | sh

Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:6 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,431 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [85.2 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,828 kB]
Hit:14 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:15 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,652 kB]
Hit:16 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,877 kB]
Get:18 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [39.2 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,301 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,780 kB]
Get:21 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,927 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,120 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,613 kB]
Fetched 40.1 MB in 4s (9,583 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
109 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libpci3 pci.ids
The following NEW packages will be installed:
  libpci3 pci.ids pciutils
0 upgraded, 3 newly installed, 0 to remove and 109 not upgraded.
Need to get 343 kB of archives.
After this operation, 1,581 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 pci.ids all 0.0~2022.01.22-1ubuntu0.1 [251 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libpci3 amd64 1:3.7.0-6 [28.9 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 pciutils amd64 1:3.7.0-6 [63.6 kB]
Fetched 343 kB in 1s (324 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package pci.ids.
(Reading database ... 121852 files and directories currently installed.)
Preparing to unpack .../pci.ids_0.0~2022.01.22-1ubuntu0.1_all.deb ...
Unpacking pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Selecting previously unselected package libpci3:amd64.
Preparing to unpack .../libpci3_1%3a3.7.0-6_amd64.deb ...
Unpacking libpci3:amd64 (1:3.7.0-6) ...
Selecting previously unselected package pciutils.
Preparing to unpack .../pciutils_1%3a3.7.0-6_amd64.deb ...
Unpacking pciutils (1:3.7.0-6) ...
Setting up pci.ids (0.0~2022.01.22-1ubuntu0.1) ...
Setting up libpci3:amd64 (1:3.7.0-6) ...
Setting up pciutils (1:3.7.0-6) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zstd
0 upgraded, 1 newly installed, 0 to remove and 109 not upgraded.
Need to get 603 kB of archives.
After this operation, 1,695 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zstd amd64 1.4.8+dfsg-3build1 [603 kB]
Fetched 603 kB in 1s (568 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package zstd.
(Reading database ... 121874 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
>>> NVIDIA GPU installed.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.

In [ ]:
# Uniquement pour Colab
import threading
import subprocess
import time

def run_ollama_serve():
  subprocess.Popen(["ollama", "serve"])

thread = threading.Thread(target=run_ollama_serve)
thread.start()
time.sleep(5)

In [ ]:
!pip install ollama

Collecting ollama
  Downloading ollama-0.6.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: httpx>=0.27 in /usr/local/lib/python3.12/dist-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in /usr/local/lib/python3.12/dist-packages (from ollama) (2.12.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27->ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9->ollama) (0.4.2)
Downloading ollama-0.6.1-py3-none-any.whl (14 kB)
Installing collected packages: ollama
Successfully installed ollama-0.6.1

In [ ]:
import pandas as pd
import ollama
import json

In [ ]:
!ollama pull gpt-oss
!ollama pull phi3

# Préparation du fichier jsonl

In [ ]:
df = pd.read_json("/content/fr-extract.jsonl.gz", lines=True, chunksize=10)
# beaucoup plus rapide que de lire le fichier avec with open
# le paramètre chunksize permet de couper mon fichier en morceaux de n lignes (ici 10 lignes par chunk)

In [ ]:
chunk = next(df) # next() permet de voir chunk par chunk, si je rerun ma cellule j'ai le chunk d'après
chunk.head(10) # visualisation des données dans le fichier

,word,lang_code,lang,pos,pos_title,etymology_texts,senses,forms,sounds,translations,...,hypernyms,related,proverbs,attestations,paronyms,descendants,meronyms,antonyms,abbreviations,raw_tags
20,ouvrage,fr,Français,noun,Nom commun,"[Dérivé de ouvrer, ancienne forme de œuvrer, a...",[{'glosses': ['Travail ; action de travailler....,"[{'form': 'ouvrages', 'tags': ['plural'], 'ipa...","[{'ipa': '\u.vʁaʒ\'}, {'ipa': '\u.vʁaʒ\'}, {'i...","[{'lang_code': 'af', 'lang': 'Afrikaans', 'wor...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,ouvrage,fr,Français,verb,Forme de verbe,"[Dérivé de ouvrer, ancienne forme de œuvrer, a...",[{'glosses': ['Première personne du singulier ...,"[{'form': 'j’ouvrage', 'tags': ['indicative', ...","[{'ipa': '\u.vʁaʒ\'}, {'ipa': '\u.vʁaʒ\'}, {'i...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,siège,fr,Français,noun,Nom commun,"[Du latin sediculum (« siège, chaise, banquett...",[{'glosses': ['Meuble utilisé pour s’asseoir.'...,"[{'form': 'sièges', 'tags': ['plural'], 'ipas'...","[{'ipa': '\sjɛʒ\'}, {'ipa': '[ɛ̃ sjɛʒ]', 'audi...","[{'lang_code': 'af', 'lang': 'Afrikaans', 'wor...",...,"[{'word': 'meuble', 'sense_index': 1}]","[{'word': 'assiéger'}, {'word': 'coussiège'}, ...",[{'word': 'mon siège est fait'}],[{'date': 'XIᵉ siècle'}],NaN,NaN,NaN,NaN,NaN,NaN
23,siège,fr,Français,verb,Forme de verbe,"[Du latin sediculum (« siège, chaise, banquett...",[{'glosses': ['Première personne du singulier ...,"[{'form': 'je siège', 'tags': ['indicative', '...","[{'ipa': '\sjɛʒ\'}, {'ipa': '[ɛ̃ sjɛʒ]', 'audi...",NaN,...,NaN,NaN,NaN,[{'date': 'XIᵉ siècle'}],NaN,NaN,NaN,NaN,NaN,NaN
24,chaise,fr,Français,noun,Nom commun,[De chaire par assibilation dialectale du \r\ ...,"[{'glosses': ['Siège avec dossier, sans accoud...","[{'form': 'chaises', 'tags': ['plural'], 'ipas...","[{'ipa': '\ʃɛz\'}, {'ipa': '\ʃez\'}, {'ipa': '...","[{'lang_code': 'af', 'lang': 'Afrikaans', 'wor...",...,[{'word': 'siège'}],NaN,NaN,NaN,[{'word': 'seize'}],"[{'lang_code': 'bm', 'lang': 'Bambara', 'word'...",NaN,NaN,NaN,NaN
25,fauteuil,fr,Français,noun,Nom commun,"[Du moyen français fauteuil, de l’ancien franç...","[{'glosses': ['Siège comportant des accotoirs,...","[{'form': 'fauteuils', 'tags': ['plural'], 'ip...","[{'ipa': '\fo.tœj\'}, {'ipa': '\fo.tœj\', 'rhy...","[{'lang_code': 'af', 'lang': 'Afrikaans', 'wor...",...,NaN,[{'word': 'chesterfield'}],NaN,[{'date': '1589'}],NaN,NaN,"[{'word': 'accoudoir'}, {'word': 'dossier'}, {...",NaN,NaN,NaN
26,fauteuil,nl,Néerlandais,noun,Nom commun,[Du français fauteuil.],"[{'glosses': ['Fauteuil.'], 'topics': ['furnit...",NaN,"[{'audio': 'Nl-fauteuil.ogg', 'ogg_url': 'http...",NaN,...,NaN,"[{'word': 'stoel'}, {'word': 'zitmeubel'}]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,meuble,fr,Français,noun,Nom commun,"[Du latin populaire *mŏbĭlis, altération, par ...","[{'glosses': ['Objet qui garnit, qui orne une ...","[{'form': 'meubles', 'tags': ['plural'], 'ipas...","[{'ipa': '\mœbl\'}, {'ipa': '\mœbl\', 'rhymes'...","[{'lang_code': 'af', 'lang': 'Afrikaans', 'wor...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,meuble,fr,Français,adj,Adjectif,"[Du latin populaire *mŏbĭlis, altération, par ...","[{'glosses': ['Caractère de ce qui est mou, ma...","[{'form': 'meubles', 'tags': ['plural', 'mascu...","[{'ipa': '\mœbl\'}, {'ipa': '\mœbl\', 'rhymes'...","[{'lang_code': 'en', 'lang': 'Anglais', 'word'...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'word': 'dur', 'sense_index': 1}, {'word': '...",NaN,NaN
29,meuble,fr,Français,verb,Forme de verbe,"[Du latin populaire *mŏbĭlis, altération, par ...",[{'glosses': ['Première personne du singulier ...,"[{'form': 'je meuble', 'tags': ['indicative', ...","[{'ipa': '\mœbl\'}, {'ipa': '\mœbl\', 'rhymes'...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
small_df = chunk[chunk["lang"] == "Français"][["word", "pos_title", "senses", "etymology_texts"]]
# on ne prend que les mots français du chunk et on fait apparaître les colonnes word, pos_title, senses et etymology_texts
# on aura besoin de ces quatre colonnes pour créer notre json_entry;
# word correspond au mot
# pos_title correspond à la catégorie
# senses correspond à la définition
# etymology_texts correspond à l'étymologie
small_df["senses"] = small_df["senses"].apply( lambda x :  x[0]["glosses"] ) # je ne prends que la première gloss
small_df = small_df.rename(columns={"word": "mot", "pos_title": "catégorie", "senses": "définition", "etymology_texts": "étymologie"})
# je renomme les colonnes pour que ça corresponde à mon fichier json_entry (et pour que ce soit en français)
small_df # df à concat avec le df de la fin (incluant les colonnes lang, base, pref, suff, comps, type)

,mot,catégorie,définition,étymologie
20,ouvrage,Nom commun,[Travail ; action de travailler.],"[Dérivé de ouvrer, ancienne forme de œuvrer, a..."
21,ouvrage,Forme de verbe,[Première personne du singulier de l’indicatif...,"[Dérivé de ouvrer, ancienne forme de œuvrer, a..."
22,siège,Nom commun,[Meuble utilisé pour s’asseoir.],"[Du latin sediculum (« siège, chaise, banquett..."
23,siège,Forme de verbe,[Première personne du singulier du présent de ...,"[Du latin sediculum (« siège, chaise, banquett..."
24,chaise,Nom commun,"[Siège avec dossier, sans accoudoirs.]",[De chaire par assibilation dialectale du \r\ ...
25,fauteuil,Nom commun,"[Siège comportant des accotoirs, et un dossier.]","[Du moyen français fauteuil, de l’ancien franç..."
27,meuble,Nom commun,"[Objet qui garnit, qui orne une chambre, un ap...","[Du latin populaire *mŏbĭlis, altération, par ..."
28,meuble,Adjectif,"[Caractère de ce qui est mou, malléable.]","[Du latin populaire *mŏbĭlis, altération, par ..."
29,meuble,Forme de verbe,[Première personne du singulier du présent de ...,"[Du latin populaire *mŏbĭlis, altération, par ..."
32,mardi,Nom commun,"[Deuxième jour de la semaine, qui suit le lund...",[Du latin Martis dies signifiant le jour de Ma...
33,mardi,Adverbe,[Le jour du mardi. Note d’usage : Peut être su...,[Du latin Martis dies signifiant le jour de Ma...
39,lundi,Nom commun,[Premier jour de la semaine de travail. Suit l...,"[De l’ancien français lunsdi, issu du latin di..."

In [ ]:
# besoin de créer une liste de toutes ces informations pour créer un fichier jsonl
# on utilise "records" pour avoir le nom des colonnes comme clés
list_of_dict = small_df.to_dict("records")
list_of_dict

[{'mot': 'ouvrage',
  'catégorie': 'Nom commun',
  'définition': ['Travail ; action de travailler.'],
  'étymologie': ['Dérivé de ouvrer, ancienne forme de œuvrer, avec le suffixe -age.']},
 {'mot': 'ouvrage',
  'catégorie': 'Forme de verbe',
  'définition': ['Première personne du singulier de l’indicatif présent du verbe ouvrager.'],
  'étymologie': ['Dérivé de ouvrer, ancienne forme de œuvrer, avec le suffixe -age.']},
 {'mot': 'siège',
  'catégorie': 'Nom commun',
  'définition': ['Meuble utilisé pour s’asseoir.'],
  'étymologie': ['Du latin sediculum (« siège, chaise, banquette ») diminutif de sedes, devenu en bas latin *sedicum de là siège. Il est lié au verbe latin sedere (« asseoir »).']},
 {'mot': 'siège',
  'catégorie': 'Forme de verbe',
  'définition': ['Première personne du singulier du présent de l’indicatif de siéger.'],
  'étymologie': ['Du latin sediculum (« siège, chaise, banquette ») diminutif de sedes, devenu en bas latin *sedicum de là siège. Il est lié au verbe latin sedere (« asseoir »).']},
 {'mot': 'chaise',
  'catégorie': 'Nom commun',
  'définition': ['Siège avec dossier, sans accoudoirs.'],
  'étymologie': ['De chaire par assibilation dialectale du \\r\\ intervocalique ; plus avant, du latin cathedra.',
   'Dans les toponymes ou noms de bâtiments (→ voir Lachaise, La Chaise-Dieu, Chaise-Dieu-du-Theil, La Chaise-Baudouin et La Chaise), issu du latin casa (« maison »).']},
 {'mot': 'fauteuil',
  'catégorie': 'Nom commun',
  'définition': ['Siège comportant des accotoirs, et un dossier.'],
  'étymologie': ['Du moyen français fauteuil, de l’ancien français faldestoed (XIIᵉ siècle), faudestuel (1165-1170) (Chrétien de Troyes), issu du vieux-francique *faldistôl (« siège pliant »).',
   'Voir falten Stuhl en allemand, pour des équivalents modernes des composés du mot.']},
 {'mot': 'meuble',
  'catégorie': 'Nom commun',
  'définition': ["Objet qui garnit, qui orne une chambre, un appartement, une maison; surtout un objet d'une taille assez importante qui sert une fonction, tel un lit, un canapé, une table, etc."],
  'étymologie': ['Du latin populaire *mŏbĭlis, altération, par analogie avec mŏvēre (« mouvoir »), du latin classique mōbĭlis (contraction de *mŏvibĭlis) (« qui peut être déplacé »).']},
 {'mot': 'meuble',
  'catégorie': 'Adjectif',
  'définition': ['Caractère de ce qui est mou, malléable.'],
  'étymologie': ['Du latin populaire *mŏbĭlis, altération, par analogie avec mŏvēre (« mouvoir »), du latin classique mōbĭlis (contraction de *mŏvibĭlis) (« qui peut être déplacé »).']},
 {'mot': 'meuble',
  'catégorie': 'Forme de verbe',
  'définition': ['Première personne du singulier du présent de l’indicatif de meubler.'],
  'étymologie': ['Du latin populaire *mŏbĭlis, altération, par analogie avec mŏvēre (« mouvoir »), du latin classique mōbĭlis (contraction de *mŏvibĭlis) (« qui peut être déplacé »).']},
 {'mot': 'mardi',
  'catégorie': 'Nom commun',
  'définition': ['Deuxième jour de la semaine, qui suit le lundi et précède le mercredi.'],
  'étymologie': ['Du latin Martis dies signifiant le jour de Mars.']},
 {'mot': 'mardi',
  'catégorie': 'Adverbe',
  'définition': ['Le jour du mardi. Note d’usage : Peut être suivi de matin, soir ou une date sans article.'],
  'étymologie': ['Du latin Martis dies signifiant le jour de Mars.']},
 {'mot': 'lundi',
  'catégorie': 'Nom commun',
  'définition': ['Premier jour de la semaine de travail. Suit le dimanche et précède le mardi.'],
  'étymologie': ['De l’ancien français lunsdi, issu du latin dies Lunae (« jour de la Lune »).']}]

In [ ]:
with open("chunk.jsonl", "w", encoding="utf-8") as f :
       for d in list_of_dict :
            f.write(json.dumps(d, ensure_ascii=False) + "\n")

In [ ]:
json_entries = []

with open("chunk.jsonl", "r", encoding="utf-8") as f :
    for line in f :
        json_entry = json.loads(line)
        json_entries.append(json_entry)

# Tests

## Sur GPT-oss

In [ ]:
llm_responses = []

SYSTEM_PROMPT = """Tu es un assistant qui répond efficacement aux questions
à partir d'un fichier JSON qui contient plusieurs informations à propos d'un mot.
Tu ne dois pas donner d'explications, tu ne dois pas raisonner, tu ne dois pas reformuler la tâche."""

for json_entry in json_entries :
  prompt = f"""l'enregistrement en JSON suivant : {json_entry} contient un mot du français, une catégorie, une définition et une étymologie. Construis un nouvel enregistrement JSON qui contient les réponses aux questions suivantes :
      * Q1 = quelle est la langue d'origine du mot qui est indiquée dans l'étymologie ? (un seul mot ou NULL si l'information est absente)
      * Q2 = quelle est la base du mot qui est indiquée dans l'étymologie ? (un seul mot ou NULL si l'information est absente)
      * Q3 = si un préfixe est indiqué dans l'étymologie, quel est ce préfixe ? (un seul mot ou NULL si l'information est absente)
      * Q4 = si un suffixe est indiqué dans l'étymologie, quel est ce suffixe ? (un seul mot ou NULL si l'information est absente)
      * Q5 = si des composants sont indiqués dans l'étymologie, quels sont ces composants ? (liste de composants ou NULL si l'information est absente)
      * Q6 = si le type du procédé morphologique est indiqué dans l'étymologie (suffixation, préfixation, composition, conversion, apocope, etc.), quel est ce type ? (un seul mot ou NULL si l'information est absente)"""

  response = ollama.chat(
          model="gpt-oss",
          messages=[
              {
                  "role": "system",
                  "content": SYSTEM_PROMPT
              },
              {"role": "user", "content": prompt},
          ],
          format="json"
      )
  print(f"Réponse : {response['message']['content']}")

  content = response["message"]["content"]
  data = json.loads(content)
  llm_responses.append(data)

Réponse : {
  "Q1": "français",
  "Q2": "accueillir",
  "Q3": null,
  "Q4": null,
  "Q5": ["accueillir"],
  "Q6": "déverbal"
}
Réponse : {
  "Q1": "latin",
  "Q2": "lĕgĕre",
  "Q3": null,
  "Q4": null,
  "Q5": null,
  "Q6": null
}
Réponse : {
  "Q1": "italien",
  "Q2": "lira",
  "Q3": null,
  "Q4": null,
  "Q5": null,
  "Q6": null
}
Réponse : {"Q1":"Latin","Q2":"encyclopaedia","Q3":"ἐγκύκλο","Q4":null,"Q5":["ἐγκύκλιος","παιδεία"],"Q6":"composition"}
Réponse : {"Q1":"latin","Q2":"encyclopaedia","Q3":"en","Q4":"ia","Q5":["ἐγκύκλιος","παιδεία"],"Q6":"composition"}
Réponse : {"Q1":"japonais","Q2":"manga","Q3":null,"Q4":null,"Q5":null,"Q6":null}

In [ ]:
df_llm_responses = pd.DataFrame(llm_responses)
df_llm_responses_modified = df_llm_responses.rename(columns={"Q1": "lang", "Q2": "base", "Q3": "pref", "Q4": "suff", "Q5": "comps", "Q6": "type"})
df_llm_responses_modified

       lang           base     pref  suff                 comps         type
0  français     accueillir     None  None          [accueillir]     déverbal
1     latin         lĕgĕre     None  None                  None         None
2   italien           lira     None  None                  None         None
3     Latin  encyclopaedia  ἐγκύκλο  None  [ἐγκύκλιος, παιδεία]  composition
4     latin  encyclopaedia       en    ia  [ἐγκύκλιος, παιδεία]  composition
5  japonais          manga     None  None                  None         None

In [ ]:
small_df_modified = small_df.rename(columns={"mot": "lemma", "catégorie": "cat", "définition": "def", "étymologie": "etym"}).reset_index(drop = True)
full_df = pd.concat([small_df_modified, df_llm_responses_modified], axis=1)
full_df

,lemma,cat,def,etym,lang,base,pref,suff,comps,type
0,accueil,Nom commun,[Cérémonie ou prestation réservée à un nouvel ...,[Déverbal de accueillir.],français,accueillir,None,None,[accueillir],déverbal
1,lire,Verbe,[Interpréter des informations écrites sous for...,"[Du latin lĕgĕre (« id. »), proprement « recue...",latin,lĕgĕre,None,None,None,None
2,lire,Nom commun,[Monnaie utilisée en Italie avant l’usage de l...,"[De l’italien lira, du latin libra (« livre »,...",italien,lira,None,None,None,None
3,encyclopédie,Nom commun,"[Ensemble, enchaînement de toutes les connaiss...",[Du latin encyclopaedia forgé à la Renaissance...,Latin,encyclopaedia,ἐγκύκλο,None,"[ἐγκύκλιος, παιδεία]",composition
4,encyclopédie,Forme de verbe,[Première personne du singulier de l’indicatif...,[Du latin encyclopaedia forgé à la Renaissance...,latin,encyclopaedia,en,ia,"[ἐγκύκλιος, παιδεία]",composition
5,manga,Nom commun,"[Bande dessinée japonaise, souvent en noir et ...","[Du japonais 漫画, manga (de même sens).]",japonais,manga,None,None,None,None

In [ ]:
full_df.to_csv("tests_gpt_oss.csv", index=False)

## Sur Phi-3

In [ ]:
SYSTEM_PROMPT = """Tu es un assistant qui répond efficacement aux questions
à partir d'un fichier JSON qui contient plusieurs informations à propos d'un mot.
Tu ne dois pas donner d'explications, tu ne dois pas raisonner, tu ne dois pas reformuler la tâche."""

for json_entry in json_entries :
  prompt = f"""l'enregistrement en JSON suivant : {json_entry} contient un mot du français, une catégorie, une définition et une étymologie. Construis un nouvel enregistrement JSON qui contient les réponses aux questions suivantes :
      * Q1 = quelle est la langue d'origine du mot qui est indiquée dans l'étymologie ? (un seul mot ou NULL si l'information est absente)
      * Q2 = quelle est la base du mot qui est indiquée dans l'étymologie ? (un seul mot ou NULL si l'information est absente)
      * Q3 = si un préfixe est indiqué dans l'étymologie, quel est ce préfixe ? (un seul mot ou NULL si l'information est absente)
      * Q4 = si un suffixe est indiqué dans l'étymologie, quel est ce suffixe ? (un seul mot ou NULL si l'information est absente)
      * Q5 = si des composants sont indiqués dans l'étymologie, quels sont ces composants ? (liste de composants ou NULL si l'information est absente)
      * Q6 = si le type du procédé morphologique est indiqué dans l'étymologie (suffixation, préfixation, composition, conversion, apocope, etc.), quel est ce type ? (un seul mot ou NULL si l'information est absente)"""

  response = ollama.chat(
          model="phi3",
          messages=[
              {
                  "role": "system",
                  "content": SYSTEM_PROMPT
              },
              {"role": "user", "content": prompt},
          ],
          format="json"
      )
  print(f"Réponse : {response['message']['content']}")

# Conclusions

GPT-oss a mieux compris la tâche : il m'a sorti des enregistrements json pour chaque entrée. Phi-3 est catastrophique : il a raisonné, a inventé des entrées qui n'étaient pas dans le prompt, les sorties ne sont pas toutes en json.

Dans l'ensemble les deux modèles ne sont pas terribles. Même si GPT-oss a bien compris la tâche, les réponses sont en partie mauvaises. Si on compare avec le tsv parsed_1, pour le lemma accueil, Nabil a trouvé que c'était une conversion alors que moi il a dit "déverbal".

**Il faut tester un meilleur modèle sur Grid5k.**