Ce notebook permet de créer un contexte avec plus d'informations étymologiques qu'on appellera "contexte étendu". Le principe est simple, nous allons étendre la colonne etym du contexte de base en remontant l'étymologie. Quand la description étymologique possède un étymon, nous allons chercher sa propre définition étymologique. Pour ce faire, nous utilisons des expressions régulières. Le processus d'extension de l'étymologie s'arrête une fois qu'aucune expression régulière ne matche avec la description étymologique.

Nous avons également extrait les déclinaisons du dernier étymon lorsqu'il en possédait.

# Imports et configuration

In [ ]:
# Uniquement pour Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Uniquement pour Colab
%cd '/content/drive/MyDrive/FAC/Master/M2/Stage/Code/Gold_context'
# path Maïwenn à changer

/content/drive/MyDrive/FAC/Master/M2/Stage/Code/Gold_context

In [ ]:
! pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 5.9 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.4.0

In [ ]:
import pandas as pd
import json
import re
from tqdm import tqdm
import ast
from bs4 import BeautifulSoup
from urllib.request import Request, urlopen
from unidecode import unidecode
import requests

#Extension du contexte

In [ ]:
df = pd.read_csv("./gold_context.csv")
df

,mot,catégorie,définition,étymologie,famille
0,lire,Verbe,['Interpréter des informations écrites sous fo...,"['Du latin lĕgĕre (« id. »), proprement «\u202...","['délire', 'entrelire', 'lisage', 'liseur', 'l..."
1,siège,Nom commun,['Meuble utilisé pour s’asseoir.'],"['Du latin sediculum (« siège, chaise, banquet...","['assiéger', 'siéger', 'télésiège', 'cul', 'de..."
2,chaise,Nom commun,"['Siège avec dossier, sans accoudoirs.']",['De chaire par assibilation dialectale du \\r...,"['chaisier', 'chaisière', 'minichaise', 'seize..."
3,fauteuil,Nom commun,"['Siège comportant des accotoirs, et un dossie...","['Du moyen français fauteuil, de l’ancien fran...","['chesterfield', 'fauteuil']"
4,oiseau,Nom commun,"['Animal vertébré théropode, à deux pattes et ...","['Du moyen français oiseau, oyseau, de l’ancie...","['antioiseau', 'oiseaulogue', 'oiselage', 'ois..."
...,...,...,...,...,...
95,coturnisme,Nom commun,['Intoxication aiguë due aux toxines sécrétées...,['Du latin coturnix « caille ».'],"['caillage', 'caille', 'caillement', 'cailler'..."
96,bibition,Nom commun,['Action de boire.'],['bas latin bibitio (« même sens »)'],"['bibition', 'boire', 'bu', 'buvable', 'buvard..."
97,thalassique,Adjectif,"['Marin, aquatique.']",['Du latin thalassicus (« couleur de la mer »).'],"['maritime', 'thalassique']"
98,thélite,Nom commun,['Inflammation du mamelon.'],"['Du grec ancien θηλή, thêlế (« mamelle ») et ...","['thélalgie', 'thélorrhagie', 'thélotisme', 'm..."
99,fabisme,Nom commun,['Variante orthographique de favisme.'],['Du latin faba (« fève ») avec le suffixe -is...,"['fabisme', 'favisme', 'fève', 'fèveraie', 'fé..."

In [ ]:
def get_all_languages_pattern() :
  url = "https://fr.wiktionary.org/wiki/Wiktionnaire:Liste_des_langues"
  req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})
  html_page = urlopen(req).read()
  soup = BeautifulSoup(html_page, 'html.parser')
  all_languages = []
  for x in soup.select('tbody>tr')[4:] :
    try :
      lg = x.select("td")[2]["data-sort-value"]
      all_languages.append(lg)
    except :
      pass
  all_languages_sorted = sorted(all_languages, key = lambda x : len(x), reverse=True)
  return "(" + "|".join(all_languages_sorted) + ")"

In [ ]:
lang_pattern = get_all_languages_pattern()
pattern1 = re.compile("(de|du|de la|de l'|de l’)\\s*" + lang_pattern + "\\s+(\\w+)", re.IGNORECASE)
pattern2 = re.compile("dérivé\\w* de (\\w+)", re.IGNORECASE)
pattern3 = re.compile("^\\w+ de (\\w+)", re.IGNORECASE)

In [ ]:
f = re.search( pattern1, "dérivé du grec ancien Ἀγαμέμνων, Agamemnon, le roi de l'Océan" )
print(f.group(3))

Ἀγαμέμνων

In [ ]:
class EtymExtension :

  def __init__(self, etym, lang) :
    self.etym = etym
    self.lang = lang
    self.next = None
    f1 = re.search(pattern1, etym)
    f2 = re.search(pattern2, etym)
    f3 = re.search(pattern3, etym)
    if f1 :
      self.next = f1.group(3)
      self.lang = f1.group(2)
      self.pattern = 1
    elif f2 :
      self.next = f2.group(1)
      self.pattern = 2
    elif f3 :
      self.next = f3.group(1)
      self.pattern = 3

  def __str__(self) :
    return "No next" if self.next is None else f'Next "{self.next}" ({self.lang}) found with pattern {self.pattern}'

  def __repr__(self) :
    return "No next" if self.next is None else f'Next "{self.next}" ({self.lang}) found with pattern {self.pattern}'

In [ ]:
ext = EtymExtension("Féminin de petraeus (« pierreux »).", "français")
print(ext)

Next "petraeus" (français) found with pattern 3

In [ ]:
ecrit_grc = "Petraea"
unidecode_treat = unidecode(ecrit_grc)
unidecode_treat

'Petraea'

In [ ]:
def search_in_kaikki(etymExtensions) :
  res = []
  for etymextension in etymExtensions :
    if etymextension is None or etymextension.next is None :
      res.append(None)
      continue
    if etymextension.lang == "latin" :
      word_next = unidecode(etymextension.next)
    else :
      word_next = etymextension.next

    url = f"https://kaikki.org/frwiktionary/All languages combined/meaning/{word_next[0]}/{word_next[:2]}/{word_next}.jsonl"

    r = requests.get(url)
    if r.status_code != 200 :
      res.append(None)
      continue

    entries = [json.loads(line) for line in r.text.strip().splitlines()]
    entries = [e for e in entries if e.get("lang", "").lower() == etymextension.lang.lower()]
    res.append(entries if entries else None)

  return res

In [ ]:
etyms = [EtymExtension(eval(etym)[0], "français") if isinstance(etym, str) else None for etym in df["étymologie"] ]
search_in_kaikki(etyms)

[[{'word': 'legere',
   'lang_code': 'la',
   'lang': 'Latin',
   'pos': 'verb',
   'pos_title': 'Forme de verbe',
   'senses': [{'glosses': ['Infinitif de lego.'],
     'tags': ['form-of'],
     'form_of': [{'word': 'lego'}]}],
   'sounds': [{'ipa': '\\le.ɡe.re\\'}],
   'categories': ['Formes de verbes en latin', 'latin'],
   'tags': ['form-of']}],
 [{'word': 'sediculum',
   'lang_code': 'la',
   'lang': 'Latin',
   'pos': 'noun',
   'pos_title': 'Nom commun',
   'etymology_texts': ['Dérivé de sedes (« siège »), avec le suffixe -culum, forme collatérale neutre\u202f^([1]) de sēdēcŭla.'],
   'senses': [{'glosses': ['Petit siège.'],
     'categories': ['Wiktionnaire:Exemples manquants en latin']}],
   'forms': [{'form': 'sedicula', 'tags': ['plural', 'nominative']},
    {'form': 'sedicula', 'tags': ['plural', 'vocative']},
    {'form': 'sedicula', 'tags': ['plural', 'accusative']},
    {'form': 'sediculī', 'tags': ['singular', 'genitive']},
    {'form': 'sediculōrum', 'tags': ['plural', 'genitive']},
    {'form': 'sediculō', 'tags': ['singular', 'dative']},
    {'form': 'sediculīs', 'tags': ['plural', 'dative']},
    {'form': 'sediculō', 'tags': ['singular', 'ablative']},
    {'form': 'sediculīs', 'tags': ['plural', 'ablative']},
    {'form': 'sēdicŭlum', 'tags': ['canonical']}],
   'categories': ['Dérivations en latin',
    'Lemmes en latin',
    'Mots en latin suffixés avec -culum',
    'Noms communs de la deuxième déclinaison en latin',
    'Noms communs en latin',
    'latin'],
   'tags': ['neuter']}],
 [{'word': 'cathedra',
   'lang_code': 'la',
   'lang': 'Latin',
   'pos': 'noun',
   'pos_title': 'Nom commun',
   'etymology_texts': ['Du grec ancien καθέδρα, kathédra.'],
   'senses': [{'glosses': ['Chaise à dossier, siège.'],
     'categories': ['Wiktionnaire:Exemples manquants en latin']},
    {'glosses': ['Chaise à porteurs.'],
     'categories': ['Wiktionnaire:Exemples manquants en latin']},
    {'glosses': ['Chaire de professeur, d’une église.'],
     'categories': ['Wiktionnaire:Exemples manquants en latin']},
    {'glosses': ['Siège épiscopal.'],
     'tags': ['figuratively'],
     'categories': ['Métaphores en latin',
      'Wiktionnaire:Exemples manquants en latin']}],
   'forms': [{'form': 'cathedră', 'tags': ['singular', 'nominative']},
    {'form': 'cathedrae', 'tags': ['plural', 'nominative']},
    {'form': 'cathedră', 'tags': ['singular', 'vocative']},
    {'form': 'cathedrae', 'tags': ['plural', 'vocative']},
    {'form': 'cathedrăm', 'tags': ['singular', 'accusative']},
    {'form': 'cathedrās', 'tags': ['plural', 'accusative']},
    {'form': 'cathedrae', 'tags': ['singular', 'genitive']},
    {'form': 'cathedrārŭm', 'tags': ['plural', 'genitive']},
    {'form': 'cathedrae', 'tags': ['singular', 'dative']},
    {'form': 'cathedrīs', 'tags': ['plural', 'dative']},
    {'form': 'cathedrā', 'tags': ['singular', 'ablative']},
    {'form': 'cathedrīs', 'tags': ['plural', 'ablative']}],
   'derived': [{'word': 'cathedralicius',
     'translation': 'fait pour les fauteuils, efféminé'},
    {'word': 'cathedralis', 'translation': 'cathédral'},
    {'word': 'cathedrarius',
     'translation': 'relatif au fauteuil ou à la chaise à porteurs ; relatif à la chaire de professeur'},
    {'word': 'cathedraticum',
     'translation': "droit d'installation en chaire"}],
   'proverbs': [{'word': 'ex cathedra',
     'translation': 'depuis la chaire, en référence à la chaire épiscopale ou pontificale, symbole d’autorité'}],
   'categories': ['Lemmes en latin',
    'Mots en latin issus d’un mot en grec ancien',
    'Noms communs de la première déclinaison en latin',
    'Noms communs en latin',
    'Wiktionnaire:Prononciations manquantes en latin',
    'latin'],
   'raw_tags': ['cathedra \\Prononciation ?\\ féminin , 1ʳᵉ déclinaison'],
   'descendants': [{'lang_code': 'en', 'lang': 'Anglais', 'word': 'chair'},
    {'lang_code': 'br', 'lang': 'Breton', 'word': 'kador'},
    {'lang_code': 'br', 'lang': 'Breton', 'word': 'kadoer'},
    {'lang_code': 'ca', 'lang': 'Catalan', 'word': 'cadira'},
    {'lang_code': 'ca', 'lang': 'Catalan', 'word': 'càtedra'},
    {'lang_code': 'es', 'lang': 'Espagnol', 'word': 'cadera'},
    {'lang_code': 'es', 'lang': 'Espagnol', 'word': 'cátedra'},
    {'lang_code': 'ga', 'lang': 'Gaélique irlandais', 'word': 'cathaoir'},
    {'lang_code': 'cy', 'lang': 'Gallois', 'word': 'cadair'},
    {'lang_code': 'it', 'lang': 'Italien', 'word': 'cattedra'},
    {'lang_code': 'fr', 'lang': 'Français', 'word': 'chaise'},
    {'lang_code': 'fr', 'lang': 'Français', 'word': 'chaire'},
    {'lang_code': 'fr', 'lang': 'Français', 'word': 'cathèdre'},
    {'lang_code': 'fr', 'lang': 'Français', 'word': 'ex cathedra'},
    {'lang_code': 'oc', 'lang': 'Occitan', 'word': 'cadièra'},
    {'lang_code': 'pcd', 'lang': 'Picard', 'word': 'caïelle'},
    {'lang_code': 'pt', 'lang': 'Portugais', 'word': 'cadeira'}]}],
 None,
 [{'word': 'avis',
   'lang_code': 'la',
   'lang': 'Latin',
   'pos': 'noun',
   'pos_title': 'Nom commun',
   'etymology_texts': ['Du radical indo-européen commun *au̯ei- (« oiseau [d’eau] »)\u202f^([1]), étroitement lié à celui de aqua d’où auca (« oie »), aquila (« aigle »), le grec ancien ἀετός, aetós (« aigle »), le breton houad (« canard »).',
    'Le Dictionnaire étymologique latin\u202f^([2]) explique au sujet de ses dérivés :',
    'La science des augures avait pris à Rome une si grande importance et avait tellement pénétré dans la vie de tous les jours, que nous trouvons le mot avis en tête d’un certain nombre de composés où on ne le soupçonnerait pas d’abord. Tels sont : au-cupari (« chercher, guetter », littéralement « guetter un présage »), au-tumare (« avérer », « affirmer »). Dans au-gurium, la seconde partie est formée d’un verbe *gurere, « éprouver » qui a donné le substantif gustus. En grec, le \\u\\ de avis est tombé et le mot s’est allongé de suffixes : οἰ-ωνός, oi-ônós (« oiseau »), αε-τός, ae-tós (« aigle »). De même, en français, avis se retrouve dans la diphtongue \\wa\\ de oiseau (= avi-cellus).'],
   'senses': [{'glosses': ['Oiseau.'],
     'categories': ['Exemples en latin'],
     'examples': [{'text': 'avis alba',
       'bold_text_offsets': [[0, 4]],
       'translation': 'un merle blanc (une chose rare).',
       'ref': 'Cicéron'}]},
    {'glosses': ['Présage, auspice.'],
     'topics': ['religion'],
     'categories': ['Exemples en latin', 'Lexique en latin de la religion'],
     'examples': [{'text': 'avis sinistra.',
       'bold_text_offsets': [[0, 4]],
       'translation': 'mauvais augure.'},
      {'text': 'secundis avibus.',
       'bold_text_offsets': [[9, 15]],
       'translation': 'avec de bons présages.'},
      {'text': 'quā avi?',
       'bold_text_offsets': [[4, 7]],
       'translation': 'par quel présage?',
       'ref': 'Plaute'}]}],
   'forms': [{'form': 'avēs', 'tags': ['plural', 'nominative']},
    {'form': 'avēs', 'tags': ['plural', 'vocative']},
    {'form': 'avĕm', 'tags': ['singular', 'accusative']},
    {'form': 'avēs', 'tags': ['plural', 'accusative']},
    {'form': 'avĭs', 'tags': ['singular', 'genitive']},
    {'form': 'aviŭm', 'tags': ['plural', 'genitive']},
    {'form': 'avī', 'tags': ['singular', 'dative']},
    {'form': 'avĭbŭs', 'tags': ['plural', 'dative']},
    {'form': 'avĕ', 'tags': ['singular', 'ablative']},
    {'form': 'avĭbŭs', 'tags': ['plural', 'ablative']},
    {'form': 'auis'}],
   'synonyms': [{'word': 'volucris'}],
   'derived': [{'word': 'aucella'},
    {'word': 'avicella'},
    {'word': 'avicellus'},
    {'word': 'avicula', 'translation': 'petit oiseau'},
    {'word': 'auceps', 'translation': 'oiseleur'},
    {'word': 'aucupalis', 'translation': 'de chasse aux oiseaux'},
    {'word': 'aucupium'},
    {'word': 'aucupatio', 'translation': 'chasse aux oiseaux'},
    {'word': 'aucupo'},
    {'word': 'aucupor', 'translation': 'chasser aux oiseaux, guetter, épier'},
    {'word': 'augur'},
    {'word': 'auguratrix',
     'translation': 'augure, interprète de la volonté des dieux lisible dans le vol des oiseaux'},
    {'word': 'auguralis', 'translation': 'augural'},
    {'word': 'auguratio',
     'translation': 'divination augurale, action de prendre les augures'},
    {'word': 'auguratorium', 'translation': 'observatoire à oiseaux'},
    {'word': 'auguratus', 'translation': 'dignité d’augure'},
    {'word': 'augurium',
     'translation': 'augure, présage donné par le vol des oiseaux'},
    {'word': 'auguro'},
    {'word': 'auguror', 'translation': 'augurer'},
    {'word': 'auspex',
     'translation': 'augure, devin qui observe le vol des oiseaux'},
    {'word': 'auspicium', 'translation': 'auspice'},
    {'word': 'auspico'},
    {'word': 'auspicor', 'translation': 'prendre les auspices'},
    {'word': 'aviarius', 'translation': "d'oiseau, aviaire"},
    {'word': 'aviarium', 'translation': 'poulailler, volière, colombier'},
    {'word': 'avicinium', 'translation': "chant d'oiseau"},
    {'word': 'inauguro', 'translation': 'inaugurer'}],
   'categories': ['Lemmes en latin',
    'Mots en latin issus d’un mot en indo-européen commun',
    'Noms communs de la troisième déclinaison en latin',
    'Noms communs en latin',
    'Oiseaux en latin',
    'latin',
    'Étymologies en latin incluant une reconstruction'],
   'raw_tags': ['avis \\ˈa.wis\\ féminin 3ᵉ déclinaison, parisyllabique']}],
 [{'word': 'diurnus',
   'lang_code': 'la',
   'lang': 'Latin',
   'pos': 'adj',
   'pos_title': 'Adjectif',
   'etymology_texts': ['Dérivé de dies (« jour »), avec le suffixe -urnus qui est aussi dans nocturnus.'],
   'senses': [{'glosses': ['Diurne.'],
     'categories': ['Wiktionnaire:Exemples manquants en latin']}],
   'forms': [{'form': 'diurnă',
     'tags': ['singular', 'feminine', 'nominative']},
    {'form': 'diurnum', 'tags': ['singular', 'neuter', 'nominative']},
    {'form': 'diurnī', 'tags': ['plural', 'masculine', 'nominative']},
    {'form': 'diurnae', 'tags': ['plural', 'feminine', 'nominative']},
    {'form': 'diurnă', 'tags': ['plural', 'neuter', 'nominative']},
    {'form': 'diurne', 'tags': ['singular', 'masculine', 'vocative']},
    {'form': 'diurnă', 'tags': ['singular', 'feminine', 'vocative']},
    {'form': 'diurnum', 'tags': ['singular', 'neuter', 'vocative']},
    {'form': 'diurnī', 'tags': ['plural', 'masculine', 'vocative']},
    {'form': 'diurnae', 'tags': ['plural', 'feminine', 'vocative']},
    {'form': 'diurnă', 'tags': ['plural', 'neuter', 'vocative']},
    {'form': 'diurnum', 'tags': ['singular', 'masculine', 'accusative']},
    {'form': 'diurnăm', 'tags': ['singular', 'feminine', 'accusative']},
    {'form': 'diurnum', 'tags': ['singular', 'neuter', 'accusative']},
    {'form': 'diurnōs', 'tags': ['plural', 'masculine', 'accusative']},
    {'form': 'diurnās', 'tags': ['plural', 'feminine', 'accusative']},
    {'form': 'diurnă', 'tags': ['plural', 'neuter', 'accusative']},
    {'form': 'diurnī', 'tags': ['singular', 'masculine', 'genitive']},
    {'form': 'diurnae', 'tags': ['singular', 'feminine', 'genitive']},
    {'form': 'diurnī', 'tags': ['singular', 'neuter', 'genitive']},
    {'form': 'diurnōrŭm', 'tags': ['plural', 'masculine', 'genitive']},
    {'form': 'diurnārŭm', 'tags': ['plural', 'feminine', 'genitive']},
    {'form': 'diurnōrŭm', 'tags': ['plural', 'neuter', 'genitive']},
    {'form': 'diurnō', 'tags': ['singular', 'masculine', 'dative']},
    {'form': 'diurnae', 'tags': ['singular', 'feminine', 'dative']},
    {'form': 'diurnō', 'tags': ['singular', 'neuter', 'dative']},
    {'form': 'diurnīs', 'tags': ['plural', 'masculine', 'dative']},
    {'form': 'diurnīs', 'tags': ['plural', 'feminine', 'dative']},
    {'form': 'diurnīs', 'tags': ['plural', 'neuter', 'dative']},
    {'form': 'diurnō', 'tags': ['singular', 'masculine', 'ablative']},
    {'form': 'diurnā', 'tags': ['singular', 'feminine', 'ablative']},
    {'form': 'diurnō', 'tags': ['singular', 'neuter', 'ablative']},
    {'form': 'diurnīs', 'tags': ['plural', 'masculine', 'ablative']},
    {'form': 'diurnīs', 'tags': ['plural', 'feminine', 'ablative']},
    {'form': 'diurnīs', 'tags': ['plural', 'neuter', 'ablative']}],
   'sounds': [{'ipa': '\\diˈuɾ.nus\\'}],
   'antonyms': [{'word': 'nocturnus'}],
   'categories': ['Adjectifs en latin',
    'Dérivations en latin',
    'Lemmes en latin',
    'Mots en latin suffixés avec -urnus',
    'latin']}],
 None,
 [{'word': 'schola',
   'lang_code': 'la',
   'lang': 'Latin',
   'pos': 'noun',
   'pos_title': 'Nom commun',
   'etymology_texts': ['Du grec ancien σχολή, skholế.'],
   'senses': [{'glosses': ['École, leçon, cours, conférence.']},
    {'glosses': ['École, lieu où se déroule l’enseignement.'],
     'categories': ['Exemples en latin'],
     'examples': [{'text': 'Non scholae sed vitae discimus.',
       'bold_text_offsets': [[4, 11]],
       'translation': 'Nous n’apprenons pas pour l’école mais pour la vie.'}]},
    {'glosses': ['École, secte philosophique.']},
    {'glosses': ['Galerie.'],
     'topics': ['architecture'],
     'categories': ['Lexique en latin de l’architecture']}],
   'forms': [{'form': 'scholă', 'tags': ['singular', 'nominative']},
    {'form': 'scholae', 'tags': ['plural', 'nominative']},
    {'form': 'scholă', 'tags': ['singular', 'vocative']},
    {'form': 'scholae', 'tags': ['plural', 'vocative']},
    {'form': 'scholăm', 'tags': ['singular', 'accusative']},
    {'form': 'scholās', 'tags': ['plural', 'accusative']},
    {'form': 'scholae', 'tags': ['singular', 'genitive']},
    {'form': 'scholārŭm', 'tags': ['plural', 'genitive']},
    {'form': 'scholae', 'tags': ['singular', 'dative']},
    {'form': 'scholīs', 'tags': ['plural', 'dative']},
    {'form': 'scholā', 'tags': ['singular', 'ablative']},
    {'form': 'scholīs', 'tags': ['plural', 'ablative']},
    {'form': 'scola'}],
   'sounds': [{'ipa': '\\ˈskʰo.la\\'}],
   'derived': [{'word': 'scholaris', 'translation': 'scolaire'}],
   'related': [{'word': 'scholasticus', 'translation': 'scolastique'},
    {'word': 'scholicus', 'translation': 'scolaire'}],
   'categories': ['Lemmes en latin',
    'Lexique en latin de l’éducation',
    'Mots en latin issus d’un mot en grec ancien',
    'Noms communs de la première déclinaison en latin',
    'Noms communs en latin',
    'latin'],
   'tags': ['feminine'],
   'descendants': [{'lang_code': 'af', 'lang': 'Afrikaans', 'word': 'skool'},
    {'lang_code': 'sq', 'lang': 'Albanais', 'word': 'shkollë'},
    {'lang_code': 'de', 'lang': 'Allemand', 'word': 'Schule'},
    {'lang_code': 'en', 'lang': 'Anglais', 'word': 'school'},
    {'lang_code': 'br', 'lang': 'Breton', 'word': 'skol'},
    {'lang_code': 'ca', 'lang': 'Catalan', 'word': 'escola'},
    {'lang_code': 'da', 'lang': 'Danois', 'word': 'skole'},
    {'lang_code': 'es', 'lang': 'Espagnol', 'word': 'escuela'},
    {'lang_code': 'et', 'lang': 'Estonien', 'word': 'kool'},
    {'lang_code': 'fi', 'lang': 'Finnois', 'word': 'koulu'},
    {'lang_code': 'fr', 'lang': 'Français', 'word': 'école'},
    {'lang_code': 'gd', 'lang': 'Gaélique écossais', 'word': 'sgoil'},
    {'lang_code': 'ga', 'lang': 'Gaélique irlandais', 'word': 'scoil'},
    {'lang_code': 'cy', 'lang': 'Gallois', 'word': 'ysgol'},
    {'lang_code': 'ka', 'lang': 'Géorgien', 'word': 'სკოლა'},
    {'lang_code': 'hu', 'lang': 'Hongrois', 'word': 'iskola'},
    {'lang_code': 'is', 'lang': 'Islandais', 'word': 'skóli'},
    {'lang_code': 'it', 'lang': 'Italien', 'word': 'scuola'},
    {'lang_code': 'nl', 'lang': 'Néerlandais', 'word': 'school'},
    {'lang_code': 'unknown', 'lang': 'unknown', 'word': 'escòla'},
    {'lang_code': 'pl', 'lang': 'Polonais', 'word': 'szkoła'},
    {'lang_code': 'pt', 'lang': 'Portugais', 'word': 'escola'},
    {'lang_code': 'ro', 'lang': 'Roumain', 'word': 'școală'},
    {'lang_code': 'ru', 'lang': 'Russe', 'word': 'школа'},
    {'lang_code': 'sk', 'lang': 'Slovaque', 'word': 'škola'},
    {'lang_code': 'sl', 'lang': 'Slovène', 'word': 'škola'},
    {'lang_code': 'sv', 'lang': 'Suédois', 'word': 'skola'},
    {'lang_code': 'sw', 'lang': 'Swahili', 'word': 'shule'},
    {'lang_code': 'cs', 'lang': 'Tchèque', 'word': 'škola'},
    {'lang_code': 'tr', 'lang': 'Turc', 'word': 'okul'}]}],
 [{'word': 'finis',
   'lang_code': 'la',
   'lang': 'Latin',
   'pos': 'noun',
   'pos_title': 'Nom commun',
   'etymology_texts': ['D’un ancien verbe *fiuo (« ficher [en terre, en paix] »)\u202f^([1]), dont le perfectif est figo (« ficher, fixer »). On fichait en terre des bornes pour limiter les territoires (→ voir meta), de là le sens de « frontière, but », etc.'],
   'senses': [{'glosses': ['Borne, limite, clôture.'],
     'categories': ['Exemples en latin'],
     'examples': [{'text': 'finem et modum transire',
       'bold_text_offsets': [[0, 5]],
       'translation': 'dépasser les bornes et la mesure.',
       'ref': 'Cicéron. Off. 1, 29, 102'}]},
    {'glosses': ['Confins, frontières.'], 'tags': ['plural']},
    {'glosses': ['Niveau, mesure, quantité, quotité, manière : l’ablatif fine (fini) suivi du génitif ou du datif : jusqu’à.'],
     'categories': ['Exemples en latin'],
     'examples': [{'text': 'fine genūs',
       'bold_text_offsets': [[0, 4]],
       'translation': "jusqu'au genou.",
       'ref': 'Ovide. M. 10'},
      {'text': 'radicibus fini',
       'bold_text_offsets': [[10, 14]],
       'translation': "jusqu'aux racines",
       'ref': 'Cat. Agr. 28, 2'}]},
    {'glosses': ['Fin, but, motif, cause, raison.'],
     'categories': ['Exemples en latin'],
     'examples': [{'text': 'domus finis est usus',
       'bold_text_offsets': [[6, 11]],
       'translation': "le but d'une maison, c'est son usage.",
       'ref': 'Cic. Off. 1, 39, 138'}]},
    {'glosses': ['Fin, cessation, terme, achèvement, bout, mort.'],
     'categories': ['Exemples en latin'],
     'examples': [{'text': 'finem loquendi facere.',
       'bold_text_offsets': [[0, 5]],
       'translation': 'cesser de parler.'},
      {'text': 'finem injuriis facere',
       'bold_text_offsets': [[0, 5]],
       'translation': 'mettre un terme aux injustices.',
       'ref': 'César. BG. 1, 33'}]},
    {'glosses': ['Définition.']}],
   'forms': [{'form': 'finēs', 'tags': ['plural', 'nominative']},
    {'form': 'finēs', 'tags': ['plural', 'vocative']},
    {'form': 'finĕm', 'tags': ['singular', 'accusative']},
    {'form': 'finēs', 'tags': ['plural', 'accusative']},
    {'form': 'finĭs', 'tags': ['singular', 'genitive']},
    {'form': 'finiŭm', 'tags': ['plural', 'genitive']},
    {'form': 'finī', 'tags': ['singular', 'dative']},
    {'form': 'finĭbŭs', 'tags': ['plural', 'dative']},
    {'form': 'finĕ', 'tags': ['singular', 'ablative']},
    {'form': 'finĭbŭs', 'tags': ['plural', 'ablative']}],
   'sounds': [{'ipa': '\\fi.nis\\'}],
   'synonyms': [{'word': 'limes'}, {'word': 'ora'}],
   'derived': [{'word': 'adfīnis', 'sense': 'Par préfixation'},
    {'word': 'affīnis',
     'translation': 'limitrophe, voisin',
     'sense': 'Par préfixation'},
    {'word': 'adfīnitas',
     'translation': 'voisinage',
     'sense': 'Par préfixation'},
    {'word': 'circumfīnio',
     'translation': 'délimiter',
     'sense': 'Par préfixation'},
    {'word': 'confīnis', 'sense': 'Par préfixation'},
    {'word': 'confīnitimus',
     'translation': 'qui confine ; qui est en rapport direct avec',
     'sense': 'Par préfixation'},
    {'word': 'confīnalis', 'sense': 'Par préfixation'},
    {'word': 'confīnialis',
     'translation': 'limitrophe',
     'sense': 'Par préfixation'},
    {'word': 'confīne',
     'translation': 'voisinage, partie limitrophe',
     'sense': 'Par préfixation'},
    {'word': 'confinium',
     'translation': 'limite commune à des champs, frontière ; proximité, voisinage',
     'sense': 'Par préfixation'},
    {'word': 'defīnio', 'translation': 'définir', 'sense': 'Par préfixation'},
    {'word': 'definitio',
     'translation': 'définition',
     'sense': 'Par préfixation'},
    {'word': 'definitivus',
     'translation': 'de définition ; définitif',

In [ ]:
def etym_extraction(kaikki_results) : # kaikki_results c'est ce qu'on obtient quand on fait serach_in_kaikki(etyms)
    if kaikki_results is None or len(kaikki_results) == 0 :
        return None
    etym = kaikki_results[0].get("etymology_texts")
    if not etym:
        return None
    return etym[0] # parce que etymology_texts est une liste dans kaikki, même si en général il n'y a qu'un élément dedans, bah nous on veut le premier

def get_extension_batchwise(etymologies, langs=None, acc=None, verbose=True) :
    if all( [x is None for x in etymologies] ) :
        return acc

    if langs is None :
        langs = ["français" for i in etymologies]
    if acc is None :
        acc = [ [] for i in etymologies ]

    if verbose:
        print("Level", len(acc[0]))

    etymExtensions = [None if etym is None else EtymExtension(etym, lang) for etym, lang in zip(etymologies, langs)]
    res = search_in_kaikki(etymExtensions)
    acc = [former + [new] for former, new in zip(acc, res)]

    next_etymologies = [etym_extraction(kaikki_results) for kaikki_results in res] # pour pouvoir analyser la string de l'étymologie extraite du fichier jsonl trouvé sur kaikki
    next_langs = [None if ext is None else ext.lang for ext in etymExtensions]

    return get_extension_batchwise(next_etymologies, next_langs, acc)

In [ ]:
etymologies = [eval(etym)[0] if isinstance(etym, str) else None for etym in df["étymologie"]]
result = get_extension_batchwise(etymologies)

Level 0
Level 1
Level 2
Level 3
Level 4

In [ ]:
etyms = []
declinaisons = []

for idx, entry in enumerate(result) :
  etym = []
  declinaison = []
  last_elem = None
  for elem in entry :
    #print(f"elem : {elem}")
    if elem is not None :
      last_elem = elem
      for d in elem :
        #print(f"dictionnaire : {d}")
        if "etymology_texts" in d :
          etym.append( d["etymology_texts"] )
  if last_elem is not None :
    definition = last_elem[0]["senses"][0]["glosses"][0]
    etym.append(definition)
    if "forms" in last_elem[0] :
      declinaison = last_elem[0]["forms"]
    #print(f"etym : {etym}")
  etyms.append(etym)
  declinaisons.append(declinaison)

df["étymologie étendue"] = etyms
df["déclinaison"] = declinaisons

In [ ]:
df

,mot,catégorie,définition,étymologie,famille,étymologie étendue,déclinaison
0,lire,Verbe,['Interpréter des informations écrites sous fo...,"['Du latin lĕgĕre (« id. »), proprement «\u202...","['délire', 'entrelire', 'lisage', 'liseur', 'l...",[Infinitif de lego.],[]
1,siège,Nom commun,['Meuble utilisé pour s’asseoir.'],"['Du latin sediculum (« siège, chaise, banquet...","['assiéger', 'siéger', 'télésiège', 'cul', 'de...","[[Dérivé de sedes (« siège »), avec le suffixe...",[]
2,chaise,Nom commun,"['Siège avec dossier, sans accoudoirs.']",['De chaire par assibilation dialectale du \\r...,"['chaisier', 'chaisière', 'minichaise', 'seize...","[[Du grec ancien καθέδρα, kathédra.], [Motcomp...",[]
3,fauteuil,Nom commun,"['Siège comportant des accotoirs, et un dossie...","['Du moyen français fauteuil, de l’ancien fran...","['chesterfield', 'fauteuil']",[],[]
4,oiseau,Nom commun,"['Animal vertébré théropode, à deux pattes et ...","['Du moyen français oiseau, oyseau, de l’ancie...","['antioiseau', 'oiseaulogue', 'oiselage', 'ois...",[[Du radical indo-européen commun *au̯ei- (« o...,"[{'form': 'avēs', 'tags': ['plural', 'nominati..."
...,...,...,...,...,...,...,...
95,coturnisme,Nom commun,['Intoxication aiguë due aux toxines sécrétées...,['Du latin coturnix « caille ».'],"['caillage', 'caille', 'caillement', 'cailler'...",[Caille.],"[{'form': 'coturnicēs', 'tags': ['plural', 'no..."
96,bibition,Nom commun,['Action de boire.'],['bas latin bibitio (« même sens »)'],"['bibition', 'boire', 'bu', 'buvable', 'buvard...",[],[]
97,thalassique,Adjectif,"['Marin, aquatique.']",['Du latin thalassicus (« couleur de la mer »).'],"['maritime', 'thalassique']","[[Du grec ancien θαλασσικός, thalassikós.], Ma...","[{'form': 'thalassică', 'tags': ['singular', '..."
98,thélite,Nom commun,['Inflammation du mamelon.'],"['Du grec ancien θηλή, thêlế (« mamelle ») et ...","['thélalgie', 'thélorrhagie', 'thélotisme', 'm...","[[De θάω, tháō (« sucer, téter »), apparenté a...","[{'form': 'θηλαί', 'tags': ['plural', 'nominat..."
99,fabisme,Nom commun,['Variante orthographique de favisme.'],['Du latin faba (« fève ») avec le suffixe -is...,"['fabisme', 'favisme', 'fève', 'fèveraie', 'fé...",[[De l’indo-européen commun *bhabha (« fruit s...,"[{'form': 'fabă', 'tags': ['singular', 'nomina..."

In [ ]:
df = df[['mot', 'catégorie', 'définition', 'étymologie', 'étymologie étendue', 'déclinaison', 'famille']]

In [ ]:
df

,mot,catégorie,définition,étymologie,étymologie étendue,déclinaison,famille
0,lire,Verbe,['Interpréter des informations écrites sous fo...,"['Du latin lĕgĕre (« id. »), proprement «\u202...",[Infinitif de lego.],[],"['délire', 'entrelire', 'lisage', 'liseur', 'l..."
1,siège,Nom commun,['Meuble utilisé pour s’asseoir.'],"['Du latin sediculum (« siège, chaise, banquet...","[[Dérivé de sedes (« siège »), avec le suffixe...",[],"['assiéger', 'siéger', 'télésiège', 'cul', 'de..."
2,chaise,Nom commun,"['Siège avec dossier, sans accoudoirs.']",['De chaire par assibilation dialectale du \\r...,"[[Du grec ancien καθέδρα, kathédra.], [Motcomp...",[],"['chaisier', 'chaisière', 'minichaise', 'seize..."
3,fauteuil,Nom commun,"['Siège comportant des accotoirs, et un dossie...","['Du moyen français fauteuil, de l’ancien fran...",[],[],"['chesterfield', 'fauteuil']"
4,oiseau,Nom commun,"['Animal vertébré théropode, à deux pattes et ...","['Du moyen français oiseau, oyseau, de l’ancie...",[[Du radical indo-européen commun *au̯ei- (« o...,"[{'form': 'avēs', 'tags': ['plural', 'nominati...","['antioiseau', 'oiseaulogue', 'oiselage', 'ois..."
...,...,...,...,...,...,...,...
95,coturnisme,Nom commun,['Intoxication aiguë due aux toxines sécrétées...,['Du latin coturnix « caille ».'],[Caille.],"[{'form': 'coturnicēs', 'tags': ['plural', 'no...","['caillage', 'caille', 'caillement', 'cailler'..."
96,bibition,Nom commun,['Action de boire.'],['bas latin bibitio (« même sens »)'],[],[],"['bibition', 'boire', 'bu', 'buvable', 'buvard..."
97,thalassique,Adjectif,"['Marin, aquatique.']",['Du latin thalassicus (« couleur de la mer »).'],"[[Du grec ancien θαλασσικός, thalassikós.], Ma...","[{'form': 'thalassică', 'tags': ['singular', '...","['maritime', 'thalassique']"
98,thélite,Nom commun,['Inflammation du mamelon.'],"['Du grec ancien θηλή, thêlế (« mamelle ») et ...","[[De θάω, tháō (« sucer, téter »), apparenté a...","[{'form': 'θηλαί', 'tags': ['plural', 'nominat...","['thélalgie', 'thélorrhagie', 'thélotisme', 'm..."
99,fabisme,Nom commun,['Variante orthographique de favisme.'],['Du latin faba (« fève ») avec le suffixe -is...,[[De l’indo-européen commun *bhabha (« fruit s...,"[{'form': 'fabă', 'tags': ['singular', 'nomina...","['fabisme', 'favisme', 'fève', 'fèveraie', 'fé..."

In [ ]:
df.to_csv("./gold_context_extended.csv", index=False)